# Change these first
owner: LightingControl # Your GitHub organization or username, where this repository lives
repo: devmonitor # The name of this repository

sites:
  - name: API DEV
    url: https://api-dev.centro.network/swagger/index.html
  - name: Frontend DEV
    url: https://dev.centro.network/api/health
  - name: App DEV
    url: https://app-dev.centro.network

  - name: API STAGE
    url: https://api-stage.centro.network/swagger/index.html
  - name: Frontend STAGE
    url: https://stage.centro.network/api/health
  - name: App STAGE
    url: https://app-stage.centro.network

  


  - name: ADMIN PANEL
    url: https://admin.centro.network
  
  - name: ADMIN Licence and Translations
    url: https://strapi.centro.network
  
  
  - name: WEBSITE 
    url: https://cms.centro.network
  - name: WEBSITE CMS
    url: https://centro.network
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: devmon.centro.network
  #baseUrl: /devmonitor
  logoUrl: https://raw.githubusercontent.com/LightingControl/devmonitor/20f47e9b7894f8df12d6c34ccbed4e982b2dddc8/assets/logo-original-dark.svg
  name: Centro Development Uptime
  introTitle: "**Centro** Development Server Status."
  introMessage: Centro Active Development Servers
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is powered by [Centro](https://centro.network)